name: reviewdog
on: [pull_request]

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Run tflint for Terraform code
      - name: Run tflint
        uses: reviewdog/action-tflint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: false
          filter_mode: added
          working_directory: terraform/
          level: info

      # Run tfsec for Terraform security issues
      - name: Run tfsec
        uses: reviewdog/action-tfsec@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: added
          fail_on_error: false
          working_directory: terraform/
          level: warning